### ISSUE TITLE
System 7.5.5 can't boot

### ISSUE THREAD

**Issue by chip-64bit** [twvd/snow#1]
Hello, this image launches on my emulator, but this one doesn't. I suspect there is a problem with the SCC emulation.
[hdd2.tar.gz](https://github.com/user-attachments/files/17368305/hdd2.tar.gz)

**Comment by twvd** [comment]
Hi, thanks for your report!

I've tested your image and it doesn't boot for me neither. I have experienced a similar issue myself with a clean System 6.0.5 install and I think it is indeed an SCC/AppleTalk emulation issue.

I will investigate.

**Comment by chip-64bit** [comment]
Hi, maybe I can give a clue, I observed in my simulator that it won't start if the scc cycle is not normal.
Something like this(c style pseudocode):
1. Can boot
while(1) {
for(...) {
    cpu_tick(10);
    via_tick(1);
    scc_tick(1);
}
}

3. Oops!!! But System 6 can boot >_<
while(1) {
for(...) {
    cpu_tick(10);
    via_tick(1);
}
scc_tick(1);
}

Thank you for your reply. Have a nice day!

> Hi, thanks for your report!
> 
> I've tested your image and it doesn't boot for me neither. I have experienced a similar issue myself with a clean System 6.0.5 install and I think it is indeed an SCC/AppleTalk emulation issue. Possibly because I'm not really emulating the SCC at all, yet, just stubbing it.
> 
> I will investigate.

Hi, maybe I can give a clue, I observed in my simulator that it won't start if the scc cycle is not normal.
Something like this(c style pseudocode):
1. Can boot
while(1) {
for(...) {
    cpu_tick(10);
    via_tick(1);
    scc_tick(1);
}
}

3. Oops!!! But System 6 can boot >_<
while(1) {
for(...) {
    cpu_tick(10);
    via_tick(1);
}
scc_tick(1);
}

Thank you for your reply. Have a nice day!

**Comment by twvd** [comment]
I've pushed a workaround that disables AppleTalk through the PRAM, for now, until I implement the SCC properly.

With that change, your disk image boots for me. Let me know if it works for you :)

(you may need to try twice because the ROM initializes the PRAM first boot)
