### ISSUE TITLE
Missing brightness setting on classic models

### ISSUE THREAD

**Issue by chip-64bit** [twvd/snow#2]
Behavior observed in other emulator:
![Screenshot_20241019_155728](https://github.com/user-attachments/assets/73777701-98ff-43ea-92ca-cd01f52f50bd)

By the way, is there a way to get help? Rust is too hard to understand, I want to rewrite in C :)
My emulator is missing VIA emulation, which is causing irregular sounds and crashes.
Do you want to rewrite this emulator to C? I can help.
[Disk Tools(battery and brightness).zip](https://github.com/user-attachments/files/17444382/Disk.Tools.battery.and.brightness.zip)

**Comment by twvd** [comment]
Hi,

Yes the brightness is missing, as are many other things, such as the sound volume etc. It's a work in progress :) I'm slowly adding more features.

I have no interest in rewriting the emulator in C. If you'd like to look at an emulator written in C, you could look at PCE, MiniVMac or MAME (C++).

**Comment by twvd** [comment]
It seems the bigger problem here is that the Mac Classic, even with the right ROM, is being detected as Mac SE by the OS. That is why the brightness control is also not showing up.

I've tried a couple of things but I cannot figure out how it detects whether the Mac is a Classic or SE (which is strange; they have different ROMs).

If you have any ideas why it is detecting the Classic as SE incorrectly, please let me know!

**Comment by twvd** [comment]
Fixed the model detection issue, the brightness control now shows up too (brightness itself is not implemented yet).

**Comment by chip-64bit** [comment]
> Fixed the model detection issue, the brightness control now shows up too (brightness itself is not implemented yet).

Wow! I've been busy debugging the ROM, how did you know that? Sorry I don't have time to reply.

**Comment by twvd** [comment]
I also spent quite some time debugging this. The Classic has a pulldown resistor on one of the VIA pins (it was used for selecting sound page on the 128K/512K). The SE does not. It seems that is how the ROM detects if it's a Classic or SE.

![signal-2024-11-28-20-53-48-973](https://github.com/user-attachments/assets/18de3af7-a2a3-4845-a285-9f6c0e92a53b)

Pretty fascinating that the Classic ROM is apparently backwards compatible with the SE. It even disables the brightness adjustment and ROM boot disk.
