### ISSUE TITLE
Failure to reboot using SCSI disk

### ISSUE THREAD

**Issue by chip-64bit** [twvd/snow#3]
Hi, SCSI disk reboot failure, on plus models.
Here's the log of its output:

16:10:53|W|snow_core::mac::bus|Read from unimplemented address: 00440000
16:10:53|W|snow_core::mac::bus|Read from unimplemented address: 00440001
16:10:53|W|snow_core::mac::bus|Read from unimplemented address: 00440002
16:10:53|W|snow_core::mac::bus|Read from unimplemented address: 00440003
16:12:25|W|snow_core::mac::bus|Read from unimplemented address: 009FFFF7
16:12:25|W|snow_core::mac::bus|Read from unimplemented address: 009FFFF9
16:12:31|W|snow_core::mac::bus|Read from unimplemented address: 00440000
16:12:31|W|snow_core::mac::bus|Read from unimplemented address: 00440001
16:12:31|W|snow_core::mac::bus|Read from unimplemented address: 00440002
16:12:31|W|snow_core::mac::bus|Read from unimplemented address: 00440003

By the way, can I ask you some questions? Thank you

**Comment by twvd** [comment]
Fixed by resetting VIA on the RESET instruction
